/* Sign-true placement lines, keyed by placement then sign. Single source of
   truth shared by the free reveal (ReadingsLanding) and the checkout sample
   excerpt (DossierCheckout) so the two can never drift. Wording moved
   VERBATIM from ReadingsLanding.tsx; do not edit lines here without a
   copy-approval. */

// Sign-true free-card lines for the three placements owners care about most.
// True to each sign's real archetype (Sun = core identity, Moon = what settles
// them, Venus = how they show love), present tense, ungendered and species-neutral
// for unnamed pets. Each names one thing the owner can actually see or feel, so it
// reads accurate rather than generic. Falls back to JOURNEY_LINES if a sign is ever
// missing.
export const SIGN_LINES: Record<string, Record<string, string>> = {
  sun: {
    Aries: "No gap between wanting and doing. First through the door, first at the food, already halfway into the thing before they have thought it through.",
    Taurus: "Slow, certain, and impossible to hurry. Comfort is a need, not a treat, and once they have picked their spot the rest of the world can wait.",
    Gemini: "Two thoughts running before they finish the first, curious about anything that moves. They take in the whole room at a glance, then need something new to do with it.",
    Cancer: "Their whole self is built around the ones they love. Soft at the center, watchful of the door, happiest when everyone they belong to is home.",
    Leo: "Made for the warm middle of the room, and they know when their seat is taken. The affection is real and generous, and it wants one pair of eyes on it. Yours.",
    Virgo: "Watchful and precise, quietly running a routine nobody assigned them. They notice the thing you moved and the second you changed your mind, and they let you know they saw.",
    Libra: "Only fully themselves when the room is calm and the bond feels even. They read your mood and hand it back a shade softer.",
    Scorpio: "All in or not at all, and they are the one who decides which. What they give, they give completely, and they forget nothing that passes between you.",
    Sagittarius: "Born mid-adventure with their nose already to the wind. The horizon is the whole point, a shut gate is a dare, and the world is theirs to go and read.",
    Capricorn: "Serious past their years, steady when everything else wobbles. They do not beg for their place, they earn it quietly, then hold it like it was always theirs.",
    Aquarius: "Their own creature on their own odd clock, and coaxing does not change it. The loyalty is real, it just arrives sideways, on terms only they understand.",
    Pisces: "Soft to the edges and tuned to whatever the room is feeling. Yours before they were their own, waiting at the door and meaning every minute of it.",
  },
  moon: {
    Aries: "Settles by burning it off, never by being told to sit still. Let the energy out first and the calm follows on its own.",
    Taurus: "Safe means warm, fed, and in the exact spot they always sleep. Move their bed a foot and you will hear about it for a week.",
    Gemini: "Calm comes from something to watch and someone to answer. A quiet, empty room is the thing that truly unsettles them, so they invent a game to fill it.",
    Cancer: "Feels safe only with you close and the day in its usual order. A skipped goodbye or a broken routine tips them into a small, wounded sulk.",
    Leo: "Feels safest the moment they are seen. A word of praise resets the whole day, and being overlooked stings far more than they let on.",
    Virgo: "Calms when everything sits in its right place. The same bowl in the same corner, the routine kept, and their anxious edge finally goes quiet.",
    Libra: "Steadies in company, frays alone. They borrow their calm straight from yours, so a tense room becomes a tense them within minutes.",
    Scorpio: "Watches from somewhere high and safe before they trust the room. Once they decide you are the one who stays, that trust is total and does not come undone.",
    Sagittarius: "Needs room and a horizon more than a soft place to lie. Open ground does more for them than any blanket could.",
    Capricorn: "Steadies on a schedule they can count on. Surprises are no gift to this one, and a day that runs to plan is a day they can finally relax into.",
    Aquarius: "Comforted by room to breathe, not by being held close. They come to you when they are ready, and letting that be the rule keeps them settled.",
    Pisces: "Soothed by quiet and the plain fact of you nearby. They soak up the whole mood of the house, so a loud day sends them under the nearest place to hide.",
  },
  venus: {
    Aries: "Loves head-on. Crashes into you, then waits, tail going, for the same back.",
    Taurus: "Shows love by leaning their whole weight on you and refusing to move.",
    Gemini: "Brings you things and talks the whole time. Attention is the love language.",
    Cancer: "Loves by guarding. Follows you room to room and frets when you leave.",
    Leo: "Loves out loud and expects it back with interest. Generous, and a little theatrical.",
    Virgo: "Shows love by staying close while you work. Missing nothing, asking for nothing.",
    Libra: "Loves to be near and in tune. Gives back the softness it wants.",
    Scorpio: "Picks one person and keeps picking them. That is you, and it is for life.",
    Sagittarius: "Loves by including you in the fun. The door is open, come on, keep up.",
    Capricorn: "Undemonstrative and completely dependable. The love is in the showing up.",
    Aquarius: "Loves on a slant. Sits one cushion away, which from them is devotion.",
    Pisces: "Loves by melting into you. No edge between their mood and yours.",
  },
  mercury: {
    Aries: "They want it now and they tell you fast. A bark, a paw, a stare, and you are already moving for them.",
    Taurus: "This one thinks slow and means it. Ask twice and you get the same calm answer, usually a look toward the food bowl.",
    Gemini: "A chatterbox brain, always two thoughts ahead. They read your tone before your words and answer with their whole body.",
    Cancer: "They speak in moods. A soft whine, a lean against your leg, and you know exactly how their day went.",
    Leo: "Everything they want comes with flair. The dramatic sigh, the head turned just so, an audience expected and usually granted.",
    Virgo: "A noticer. This one clocks the new bag, the rearranged shoes, the half-second you paused, and lets you know they saw.",
    Libra: "They negotiate. A look at you, a look at the door, a polite pause until you both agree on the plan.",
    Scorpio: "Quiet and watchful, this one says little and means all of it. When they finally ask, you do not say no.",
    Sagittarius: "Big loud opinions about everything outside. They tell you the squirrel is back, the mail came, the neighbor exists.",
    Capricorn: "A serious communicator. One firm look that means business, and they hold your eye until the message lands.",
    Aquarius: "This one invents their own signals. An odd tap, a specific yowl, a routine only the two of you understand.",
    Pisces: "They read the room before you do. A change in your voice and they are already at your feet, asking nothing, offering everything.",
  },
  mars: {
    Aries: "First out the door, last to quit. This one plays rough, forgives fast, and treats every squirrel like a personal challenge.",
    Taurus: "Slow to rile, impossible to budge once they are. They want what they want and will lean their whole weight into getting it.",
    Gemini: "Energy comes in quick bursts and changes targets mid-pounce. This one would rather outsmart you than out-muscle you.",
    Cancer: "Defends their people before themselves. Gentle until something they love is threatened, then suddenly very brave.",
    Leo: "Plays to an audience and fights for the spotlight. Bold, a little dramatic, and genuinely proud of the prize they bring you.",
    Virgo: "Goes after what they want with quiet precision, not noise. This one studies the problem, then solves it on the third try.",
    Libra: "Hates a real fight, loves a fair game. They will charm their way to the treat long before they wrestle for it.",
    Scorpio: "All or nothing, and they remember. This one locks onto a goal with a focus that is a little intense.",
    Sagittarius: "Runs first, thinks later, and the whole world is the playing field. Restless, fearless, happiest in full sprint.",
    Capricorn: "Patient and relentless. This one paces themselves, never wastes a move, and quietly wins the long game.",
    Aquarius: "Picks their own fights for their own reasons. Stubborn in odd moments, unbothered in the ones you expect to spook them.",
    Pisces: "Goes soft and sideways rather than head-on. Their drive runs on feeling, so a sulk hits harder than any growl.",
  },
  jupiter: {
    Aries: "This one trusts fast and barrels into the new dog at the park like it is a personal invitation. Lucky when bold, sore when reckless.",
    Taurus: "They open up over food and a warm lap, and they open up a lot. Good fortune smells like a full bowl, twice.",
    Gemini: "This one expands by sniffing everything and trusting whoever talks to them. Curiosity pays off, until it leads them three gardens over.",
    Cancer: "They trust the ones who feel like home, then love them past all reason. Their luck lives indoors, near you.",
    Leo: "This one believes the whole room exists to admire them, and somehow it usually does. They give affection like a standing ovation.",
    Virgo: "They trust slowly, watch you first, then quietly devote themselves to one good routine. Their luck hides in small, useful habits.",
    Libra: "This one opens up to make peace and charms everyone into liking them. They overdo the sweetness, hoping nobody ever leaves.",
    Scorpio: "They trust deep or not at all, and once they pick you it is total. Fortune favors them when they finally let go.",
    Sagittarius: "This one believes every open door leads somewhere good and bolts through it grinning. Born lucky, terrible at staying in the yard.",
    Capricorn: "They trust what is earned and expand on their own slow schedule. Their good fortune comes late, then stays for good.",
    Aquarius: "This one trusts oddly, warming to the one stranger nobody expected. Their luck arrives sideways and never how you planned.",
    Pisces: "They open up to everyone and feel the whole room at once, sometimes too much. Their luck flows in on a gentle, dreamy tide.",
  },
  saturn: {
    Aries: "Saturn keeps a short leash on this one. Caution comes in late and grudgingly, usually after they have already charged at the thing.",
    Taurus: "This one holds the line by simply not moving. Routine is their fortress, and they will wait out any change you try to introduce.",
    Gemini: "Their caution is mental, not physical. They will watch a new object from three angles before deciding it is allowed to exist.",
    Cancer: "This one guards what feels like home and gets stern about it. Trust is slow, but once given it does not waver.",
    Leo: "Pride is their discipline. They hold back to keep their dignity intact, and they hate being caught making a mistake.",
    Virgo: "This one polices the small stuff. A bowl out of place, a strange smell, and they go quietly, watchfully serious about it.",
    Libra: "Their boundaries are about fairness. They hold back until they have weighed both sides, then commit with surprising steadiness.",
    Scorpio: "This one trusts almost nothing at first. The walls are thick and deliberate, and earning a way past them takes real time.",
    Sagittarius: "Discipline sits uneasy on this one. They accept limits only when they understand the reason, and they test every fence twice.",
    Capricorn: "Saturn is right at home here. This one is self-governed, patient, and oddly responsible, the old soul who waits its turn.",
    Aquarius: "Their boundaries are on their own terms. They keep a cool distance, then choose exactly when and whom to let close.",
    Pisces: "Caution dissolves and reforms in this one. They retreat softly when overwhelmed, needing quiet to rebuild their edges.",
  },
  uranus: {
    Aries: "This one bolts off mid-walk for no reason they will share, then acts like it was your idea all along.",
    Taurus: "Stubbornly the same for years, then one day they decide the sofa is theirs now and that is simply the new law.",
    Gemini: "Their attention snaps to a new game every few minutes. You never quite predict which sound sets them off next.",
    Cancer: "Cuddly and steady until a tiny change in the room, a moved chair, a new smell, flips them into a different mood entirely.",
    Leo: "Right when all eyes are on them, they ditch the trick they know and freestyle something stranger and louder.",
    Virgo: "They keep a tidy routine, then rearrange one small ritual overnight and expect you to have noticed already.",
    Libra: "Easygoing about most things, then out of nowhere they refuse a friend they have always liked, and will not be talked round.",
    Scorpio: "Their surprises run deep and quiet. One day they show a hiding spot or a trust you had no idea was being weighed.",
    Sagittarius: "Fences are suggestions. This one finds the one gap you missed and treats the whole neighbourhood as fair territory.",
    Capricorn: "Predictable to a fault, then they break a rule they built themselves, calmly, like they have simply outgrown it.",
    Aquarius: "The genuine odd one. They invent private rituals, ignore the usual pet script, and seem to run on their own logic.",
    Pisces: "Their moods arrive like weather, no warning, no clear cause. One minute dreamy, the next darting somewhere only they understand.",
  },
  neptune: {
    Aries: "Dreams in fast-forward, then forgets them. This one zones out mid-zoomie, snaps back like they meant to do that.",
    Taurus: "Naps with the dedication of a professional. This one drifts off in any patch of sun and takes their sweet time waking.",
    Gemini: "A short attention span for the real world, endless for whatever they imagine. This one chases shadows that are not there.",
    Cancer: "Feels your mood before you say a word, then goes quiet and clingy to match it. A little sponge for the room.",
    Leo: "Stares into the middle distance like they are in a film about themselves. This one daydreams in the spotlight, even an empty one.",
    Virgo: "Worries and wanders at once. This one fusses over a corner of the rug, then forgets why and stares at the wall.",
    Libra: "Soft on everyone, hard to read. This one floats between laps, half here, dissolving into whoever is gentlest.",
    Scorpio: "Senses things you cannot and will not explain. This one fixes on a closed door, ears back, lost in something only they hear.",
    Sagittarius: "Wanders off mid-thought, nose in the clouds. This one forgets where they buried the toy and looks delighted anyway.",
    Capricorn: "Quietly tender under the serious face. This one keeps a routine, then melts into a long, faraway stare at nothing.",
    Aquarius: "Off in their own orbit. This one ignores the obvious, then fixates on a speck of dust like it holds answers.",
    Pisces: "Made of feelings and fog. This one slips into sleep mid-cuddle, dreams loudly, and wakes unsure which world they are in.",
  },
  pluto: {
    Aries: "Their intensity comes out fast and physical. Push them and they push back, then forget the whole thing by dinner.",
    Taurus: "They hold on hard and quietly. A favorite spot, a routine, one person. Try to move any of it and you meet the wall.",
    Gemini: "Their deep stuff hides behind chatter and games. Watch closely and you catch a sharper, watchful mind under the goofing.",
    Cancer: "They feel everything and bury most of it. A closed door or a packed bag can shake this one for days.",
    Leo: "Their need for control runs through pride. They want to be seen, and being ignored cuts deeper than they let on.",
    Virgo: "Their tension lives in the details. One thing out of place and this one fixates, grooming or pacing until it feels right.",
    Libra: "They keep the peace by hiding what bothers them. The unrest leaks out sideways, in sulks and pointed silences.",
    Scorpio: "All in, all the time. This one bonds to the bone, reads your moods, and never quite forgets a betrayal.",
    Sagittarius: "Their intensity needs somewhere to run. Pen them in and the pressure turns to chewing, digging, or a sudden bolt for the door.",
    Capricorn: "They carry their guard like a job. Slow to trust, steady once they do, and quietly stubborn about who runs the house.",
    Aquarius: "Their depths stay private and a little odd. They watch the room from the edge and decide, on their own terms, when to come close.",
    Pisces: "They soak up the mood of the whole house and rarely show where it lands. The quiet ones often feel the most.",
  },
  chiron: {
    Aries: "This one bruises when overlooked or told to wait their turn. They mend by being the first one greeted, the one you reach for.",
    Taurus: "A quiet fear of going without sits in this one, leftover from leaner days. A full bowl and a warm spot, kept steady, settles it.",
    Gemini: "This one was hushed once, maybe ignored when they tried to say something. They heal when you answer their little sounds like real talk.",
    Cancer: "The old ache here is being left. They flinch at closed doors and packed bags, and soften when you come back and mean it.",
    Leo: "Somewhere this one learned they were too much. They steady when the attention they crave is given freely, not earned by performing.",
    Virgo: "This one frets over getting it wrong, bracing for a scold that may never come. Gentle routine and praise for small things loosen the worry.",
    Libra: "A tension between people unsettles this one deeply. Raised voices land as their fault, and they mend in a calm, even-keeled home.",
    Scorpio: "This one guards an old betrayal and trusts slowly. They heal in increments, each kept promise loosening the grip a little more.",
    Sagittarius: "A clipped life or a small cage once shrank this one's world. They knit back together with open space and the freedom to wander it.",
    Capricorn: "This one carries themself like they must earn their keep, never quite resting. Being loved for nothing in particular is the slow cure.",
    Aquarius: "A sense of not fitting follows this one, the odd one in any group. They settle once they find their one person and stop reaching for the rest.",
    Pisces: "This one soaks up the mood of the house and aches when it sours. Quiet, a soft blanket, and your steady calm draw the heaviness back out.",
  },
  northNode: {
    Aries: "Life with you is teaching this one to act first and ask later, to want something and just go get it.",
    Taurus: "This one is settling into steadiness, learning that the same warm spot and the same routine are their own reward.",
    Gemini: "Your pet is growing curious, learning to take an interest in everything, every sound, every new face at the door.",
    Cancer: "This one is softening into a home creature, learning to need you back and to let themselves be looked after.",
    Leo: "Life with you is coaxing out the show-off, the one who learns it is fine to want the spotlight and take it.",
    Virgo: "Your pet is growing into small daily habits, finding calm in being useful, tidy, and quietly on top of things.",
    Libra: "This one is learning the give and take of company, how to read your mood and meet you halfway.",
    Scorpio: "This one is growing toward deep, all-in attachment, the kind that bonds to one person and means it.",
    Sagittarius: "Life with you is opening this one up, teaching them to trust the next walk, the next car, the next adventure.",
    Capricorn: "Your pet is steadily learning patience and self-control, growing into the calm, dependable one of the house.",
    Aquarius: "This one is becoming their own odd self, learning it is fine to like things on their own terms.",
    Pisces: "This one is growing gentler and more tuned in, learning to feel what you feel and curl close when you need it.",
  },
  lilith: {
    Aries: "The thing in them that bolts the second a leash goes slack. Their wildness has no patience and no off switch.",
    Taurus: "Will not be moved when they have decided otherwise. The untamed part of them is just a body planted like a boulder.",
    Gemini: "Their feral streak talks back. It darts, dodges, and pretends not to hear you, always one trick ahead.",
    Cancer: "Guards something private that nobody gets to touch. Push too close and the soft one shows teeth.",
    Leo: "Refuses to be a pet on anyone's terms. Their wild side wants the room, the spotlight, and the last word.",
    Virgo: "Their untamed part hides in the details, the secret stash, the spot they will not let you clean. Quietly ungovernable.",
    Libra: "Charming until you cross a line they never named. Then the sweet one simply stops cooperating, all grace, zero compliance.",
    Scorpio: "Keeps a wildness it never shows you. What this one wants, it stalks in total silence until the moment comes.",
    Sagittarius: "The part that treats a fence as a suggestion. Their freedom is non-negotiable and the door is always a dare.",
    Capricorn: "Submits to nothing, just waits you out. The untamed thing in them is patient, cold, and absolutely in charge.",
    Aquarius: "Cannot be trained into anyone's idea of normal. Their wildness is the rule they broke on purpose.",
    Pisces: "Slips your grip like water and goes somewhere you cannot follow. The wild one here is half here, half elsewhere.",
  },
};
