import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'it' | 'ja' | 'zh' | 'ko' | 'nl' | 'ru' | 'ar';

export const languages: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation files
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.howItWorks': 'How it Works',
    'nav.testimonials': 'Testimonials',
    'nav.faq': 'FAQ',
    'nav.gift': 'Gift a Reading',
    'nav.getReading': 'Get Your Reading',
    
    // Hero
    'hero.badge': '✨ Trusted by 10,000+ Pet Parents',
    'hero.title': 'Discover Your Pet\'s',
    'hero.titleHighlight': 'Cosmic Soul',
    'hero.subtitle': 'Unlock the mystical secrets written in the stars the day your pet was born. A personalized astrological journey that reveals their true nature, hidden quirks, and the cosmic bond you share.',
    'hero.cta': 'Reveal Their Cosmic Portrait',
    'hero.ctaSubtext': '🌟 Instant digital delivery • 100% personalized',
    'hero.trustpilot': 'Excellent',
    'hero.reviews': 'Based on 2,847 reviews',
    
    // How it Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Three simple steps to unlock your pet\'s cosmic secrets',
    'howItWorks.step1.title': 'Share Their Details',
    'howItWorks.step1.desc': 'Tell us about your pet - their birth date, personality traits, and what makes them special.',
    'howItWorks.step2.title': 'We Consult the Stars',
    'howItWorks.step2.desc': 'Our cosmic algorithms analyze planetary positions and create a unique astrological profile.',
    'howItWorks.step3.title': 'Receive Your Report',
    'howItWorks.step3.desc': 'Get a beautifully crafted, personalized cosmic portrait delivered instantly to your inbox.',
    
    // Testimonials
    'testimonials.title': 'What Pet Parents Say',
    'testimonials.subtitle': 'Join thousands who\'ve discovered their pet\'s cosmic truth',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about your pet\'s cosmic reading',
    
    // Footer
    'footer.tagline': 'Revealing the cosmic bond between you and your beloved companion.',
    'footer.links': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2024 The Cosmic Pet. All rights reserved.',
    
    // Intake
    'intake.letsBegin': 'Let\'s Begin Your Cosmic Journey',
    'intake.petName': 'What\'s your pet\'s name?',
    'intake.petNamePlaceholder': 'Enter their name...',
    'intake.species': 'What kind of companion are they?',
    'intake.breed': 'What breed is',
    'intake.breedPlaceholder': 'Search breeds...',
    'intake.gender': 'Is {name} a boy or girl?',
    'intake.boy': 'Boy',
    'intake.girl': 'Girl',
    'intake.dob': 'When was {name} born?',
    'intake.dobApprox': 'Approximate date is fine!',
    'intake.location': 'Where was {name} born?',
    'intake.locationPlaceholder': 'City or region...',
    'intake.soul': 'Which describes {name}\'s soul?',
    'intake.superpower': 'What\'s {name}\'s superpower?',
    'intake.strangers': 'How does {name} act with strangers?',
    'intake.email': 'Where should we send the cosmic report?',
    'intake.emailPlaceholder': 'your@email.com',
    'intake.continue': 'Continue',
    'intake.back': 'Back',
    
    // Checkout
    'checkout.title': 'Choose Your Cosmic Package',
    'checkout.basic': 'Basic Reading',
    'checkout.premium': 'Premium Reading',
    'checkout.vip': 'VIP Experience',
    'checkout.popular': 'Most Popular',
    'checkout.bestValue': 'Best Value',
    'checkout.unlock': 'Unlock Report',
    'checkout.addGift': 'Add as a Gift',
    'checkout.volumeDiscount': 'Volume discount:',
    
    // Report
    'report.generating': 'Consulting the Stars...',
    'report.generatingDesc': 'The cosmos is aligning to reveal {name}\'s true nature',
    'report.download': 'Download PDF',
    'report.share': 'Share',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.tryAgain': 'Try Again',
    'common.selectLanguage': 'Select Language',
  },
  es: {
    // Navbar
    'nav.howItWorks': 'Cómo Funciona',
    'nav.testimonials': 'Testimonios',
    'nav.faq': 'Preguntas',
    'nav.gift': 'Regalar una Lectura',
    'nav.getReading': 'Obtén Tu Lectura',
    
    // Hero
    'hero.badge': '✨ Más de 10,000 Padres de Mascotas Confían',
    'hero.title': 'Descubre el',
    'hero.titleHighlight': 'Alma Cósmica',
    'hero.subtitle': 'Desbloquea los secretos místicos escritos en las estrellas el día que nació tu mascota. Un viaje astrológico personalizado que revela su verdadera naturaleza, peculiaridades ocultas y el vínculo cósmico que comparten.',
    'hero.cta': 'Revela Su Retrato Cósmico',
    'hero.ctaSubtext': '🌟 Entrega digital instantánea • 100% personalizado',
    'hero.trustpilot': 'Excelente',
    'hero.reviews': 'Basado en 2,847 reseñas',
    
    // How it Works
    'howItWorks.title': 'Cómo Funciona',
    'howItWorks.subtitle': 'Tres simples pasos para desbloquear los secretos cósmicos de tu mascota',
    'howItWorks.step1.title': 'Comparte Sus Detalles',
    'howItWorks.step1.desc': 'Cuéntanos sobre tu mascota - su fecha de nacimiento, rasgos de personalidad y qué los hace especiales.',
    'howItWorks.step2.title': 'Consultamos las Estrellas',
    'howItWorks.step2.desc': 'Nuestros algoritmos cósmicos analizan las posiciones planetarias y crean un perfil astrológico único.',
    'howItWorks.step3.title': 'Recibe Tu Informe',
    'howItWorks.step3.desc': 'Obtén un retrato cósmico personalizado bellamente elaborado, entregado instantáneamente a tu correo.',
    
    // Testimonials
    'testimonials.title': 'Lo Que Dicen los Padres de Mascotas',
    'testimonials.subtitle': 'Únete a miles que han descubierto la verdad cósmica de sus mascotas',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Todo lo que necesitas saber sobre la lectura cósmica de tu mascota',
    
    // Footer
    'footer.tagline': 'Revelando el vínculo cósmico entre tú y tu amado compañero.',
    'footer.links': 'Enlaces Rápidos',
    'footer.legal': 'Legal',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.copyright': '© 2024 The Cosmic Pet. Todos los derechos reservados.',
    
    // Intake
    'intake.letsBegin': 'Comencemos Tu Viaje Cósmico',
    'intake.petName': '¿Cómo se llama tu mascota?',
    'intake.petNamePlaceholder': 'Ingresa su nombre...',
    'intake.species': '¿Qué tipo de compañero es?',
    'intake.breed': '¿Qué raza es',
    'intake.breedPlaceholder': 'Buscar razas...',
    'intake.gender': '¿{name} es niño o niña?',
    'intake.boy': 'Niño',
    'intake.girl': 'Niña',
    'intake.dob': '¿Cuándo nació {name}?',
    'intake.dobApprox': '¡Una fecha aproximada está bien!',
    'intake.location': '¿Dónde nació {name}?',
    'intake.locationPlaceholder': 'Ciudad o región...',
    'intake.soul': '¿Cuál describe el alma de {name}?',
    'intake.superpower': '¿Cuál es el superpoder de {name}?',
    'intake.strangers': '¿Cómo actúa {name} con extraños?',
    'intake.email': '¿A dónde enviamos el informe cósmico?',
    'intake.emailPlaceholder': 'tu@email.com',
    'intake.continue': 'Continuar',
    'intake.back': 'Atrás',
    
    // Checkout
    'checkout.title': 'Elige Tu Paquete Cósmico',
    'checkout.basic': 'Lectura Básica',
    'checkout.premium': 'Lectura Premium',
    'checkout.vip': 'Experiencia VIP',
    'checkout.popular': 'Más Popular',
    'checkout.bestValue': 'Mejor Valor',
    'checkout.unlock': 'Desbloquear Informe',
    'checkout.addGift': 'Agregar como Regalo',
    'checkout.volumeDiscount': 'Descuento por volumen:',
    
    // Report
    'report.generating': 'Consultando las Estrellas...',
    'report.generatingDesc': 'El cosmos se está alineando para revelar la verdadera naturaleza de {name}',
    'report.download': 'Descargar PDF',
    'report.share': 'Compartir',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Algo salió mal',
    'common.tryAgain': 'Intentar de Nuevo',
    'common.selectLanguage': 'Seleccionar Idioma',
  },
  fr: {
    'nav.howItWorks': 'Comment ça Marche',
    'nav.testimonials': 'Témoignages',
    'nav.faq': 'FAQ',
    'nav.gift': 'Offrir une Lecture',
    'nav.getReading': 'Obtenir Votre Lecture',
    'hero.badge': '✨ Plus de 10 000 Parents d\'Animaux Font Confiance',
    'hero.title': 'Découvrez l\'',
    'hero.titleHighlight': 'Âme Cosmique',
    'hero.subtitle': 'Débloquez les secrets mystiques écrits dans les étoiles le jour où votre animal est né. Un voyage astrologique personnalisé qui révèle leur vraie nature, leurs bizarreries cachées et le lien cosmique que vous partagez.',
    'hero.cta': 'Révéler Leur Portrait Cosmique',
    'hero.ctaSubtext': '🌟 Livraison numérique instantanée • 100% personnalisé',
    'hero.trustpilot': 'Excellent',
    'hero.reviews': 'Basé sur 2 847 avis',
    'howItWorks.title': 'Comment ça Marche',
    'howItWorks.subtitle': 'Trois étapes simples pour débloquer les secrets cosmiques de votre animal',
    'howItWorks.step1.title': 'Partagez Leurs Détails',
    'howItWorks.step1.desc': 'Parlez-nous de votre animal - sa date de naissance, ses traits de personnalité et ce qui le rend spécial.',
    'howItWorks.step2.title': 'Nous Consultons les Étoiles',
    'howItWorks.step2.desc': 'Nos algorithmes cosmiques analysent les positions planétaires et créent un profil astrologique unique.',
    'howItWorks.step3.title': 'Recevez Votre Rapport',
    'howItWorks.step3.desc': 'Obtenez un portrait cosmique personnalisé magnifiquement conçu, livré instantanément dans votre boîte mail.',
    'testimonials.title': 'Ce Que Disent les Parents d\'Animaux',
    'testimonials.subtitle': 'Rejoignez des milliers qui ont découvert la vérité cosmique de leur animal',
    'faq.title': 'Questions Fréquentes',
    'faq.subtitle': 'Tout ce que vous devez savoir sur la lecture cosmique de votre animal',
    'footer.tagline': 'Révéler le lien cosmique entre vous et votre compagnon bien-aimé.',
    'footer.links': 'Liens Rapides',
    'footer.legal': 'Légal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.copyright': '© 2024 The Cosmic Pet. Tous droits réservés.',
    'intake.letsBegin': 'Commençons Votre Voyage Cosmique',
    'intake.petName': 'Comment s\'appelle votre animal?',
    'intake.petNamePlaceholder': 'Entrez son nom...',
    'intake.species': 'Quel type de compagnon est-ce?',
    'intake.breed': 'Quelle est la race de',
    'intake.breedPlaceholder': 'Rechercher des races...',
    'intake.gender': '{name} est un garçon ou une fille?',
    'intake.boy': 'Garçon',
    'intake.girl': 'Fille',
    'intake.dob': 'Quand est né(e) {name}?',
    'intake.dobApprox': 'Une date approximative suffit!',
    'intake.location': 'Où est né(e) {name}?',
    'intake.locationPlaceholder': 'Ville ou région...',
    'intake.soul': 'Qu\'est-ce qui décrit l\'âme de {name}?',
    'intake.superpower': 'Quel est le superpouvoir de {name}?',
    'intake.strangers': 'Comment {name} agit-il avec les étrangers?',
    'intake.email': 'Où devons-nous envoyer le rapport cosmique?',
    'intake.emailPlaceholder': 'votre@email.com',
    'intake.continue': 'Continuer',
    'intake.back': 'Retour',
    'checkout.title': 'Choisissez Votre Forfait Cosmique',
    'checkout.basic': 'Lecture de Base',
    'checkout.premium': 'Lecture Premium',
    'checkout.vip': 'Expérience VIP',
    'checkout.popular': 'Plus Populaire',
    'checkout.bestValue': 'Meilleure Valeur',
    'checkout.unlock': 'Débloquer le Rapport',
    'checkout.addGift': 'Ajouter comme Cadeau',
    'checkout.volumeDiscount': 'Remise volume:',
    'report.generating': 'Consultation des Étoiles...',
    'report.generatingDesc': 'Le cosmos s\'aligne pour révéler la vraie nature de {name}',
    'report.download': 'Télécharger PDF',
    'report.share': 'Partager',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.tryAgain': 'Réessayer',
    'common.selectLanguage': 'Sélectionner la Langue',
  },
  de: {
    'nav.howItWorks': 'So Funktioniert\'s',
    'nav.testimonials': 'Bewertungen',
    'nav.faq': 'FAQ',
    'nav.gift': 'Reading Verschenken',
    'nav.getReading': 'Ihr Reading Erhalten',
    'hero.badge': '✨ Über 10.000 Tiereltern Vertrauen Uns',
    'hero.title': 'Entdecke die',
    'hero.titleHighlight': 'Kosmische Seele',
    'hero.subtitle': 'Entschlüsseln Sie die mystischen Geheimnisse, die am Tag der Geburt Ihres Haustieres in den Sternen geschrieben wurden. Eine personalisierte astrologische Reise, die ihre wahre Natur, versteckte Eigenheiten und die kosmische Bindung offenbart.',
    'hero.cta': 'Ihr Kosmisches Portrait Enthüllen',
    'hero.ctaSubtext': '🌟 Sofortige digitale Lieferung • 100% personalisiert',
    'hero.trustpilot': 'Ausgezeichnet',
    'hero.reviews': 'Basierend auf 2.847 Bewertungen',
    'howItWorks.title': 'So Funktioniert\'s',
    'howItWorks.subtitle': 'Drei einfache Schritte, um die kosmischen Geheimnisse Ihres Haustieres zu entschlüsseln',
    'howItWorks.step1.title': 'Details Teilen',
    'howItWorks.step1.desc': 'Erzählen Sie uns von Ihrem Haustier - Geburtsdatum, Persönlichkeitsmerkmale und was sie besonders macht.',
    'howItWorks.step2.title': 'Wir Befragen die Sterne',
    'howItWorks.step2.desc': 'Unsere kosmischen Algorithmen analysieren Planetenpositionen und erstellen ein einzigartiges astrologisches Profil.',
    'howItWorks.step3.title': 'Bericht Erhalten',
    'howItWorks.step3.desc': 'Erhalten Sie ein wunderschön gestaltetes, personalisiertes kosmisches Portrait, sofort in Ihrem Postfach.',
    'testimonials.title': 'Was Tiereltern Sagen',
    'testimonials.subtitle': 'Schließen Sie sich Tausenden an, die die kosmische Wahrheit ihrer Haustiere entdeckt haben',
    'faq.title': 'Häufig Gestellte Fragen',
    'faq.subtitle': 'Alles, was Sie über das kosmische Reading Ihres Haustieres wissen müssen',
    'footer.tagline': 'Die kosmische Bindung zwischen Ihnen und Ihrem geliebten Begleiter enthüllen.',
    'footer.links': 'Schnelllinks',
    'footer.legal': 'Rechtliches',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.copyright': '© 2024 The Cosmic Pet. Alle Rechte vorbehalten.',
    'intake.letsBegin': 'Beginnen Sie Ihre Kosmische Reise',
    'intake.petName': 'Wie heißt Ihr Haustier?',
    'intake.petNamePlaceholder': 'Namen eingeben...',
    'intake.species': 'Was für ein Begleiter ist es?',
    'intake.breed': 'Welche Rasse ist',
    'intake.breedPlaceholder': 'Rassen suchen...',
    'intake.gender': 'Ist {name} ein Junge oder Mädchen?',
    'intake.boy': 'Junge',
    'intake.girl': 'Mädchen',
    'intake.dob': 'Wann wurde {name} geboren?',
    'intake.dobApprox': 'Ein ungefähres Datum ist in Ordnung!',
    'intake.location': 'Wo wurde {name} geboren?',
    'intake.locationPlaceholder': 'Stadt oder Region...',
    'intake.soul': 'Was beschreibt {name}s Seele?',
    'intake.superpower': 'Was ist {name}s Superkraft?',
    'intake.strangers': 'Wie verhält sich {name} bei Fremden?',
    'intake.email': 'Wohin sollen wir den kosmischen Bericht senden?',
    'intake.emailPlaceholder': 'ihre@email.com',
    'intake.continue': 'Weiter',
    'intake.back': 'Zurück',
    'checkout.title': 'Wählen Sie Ihr Kosmisches Paket',
    'checkout.basic': 'Basis Reading',
    'checkout.premium': 'Premium Reading',
    'checkout.vip': 'VIP Erlebnis',
    'checkout.popular': 'Am Beliebtesten',
    'checkout.bestValue': 'Bester Wert',
    'checkout.unlock': 'Bericht Freischalten',
    'checkout.addGift': 'Als Geschenk Hinzufügen',
    'checkout.volumeDiscount': 'Mengenrabatt:',
    'report.generating': 'Die Sterne Befragen...',
    'report.generatingDesc': 'Der Kosmos richtet sich aus, um {name}s wahre Natur zu enthüllen',
    'report.download': 'PDF Herunterladen',
    'report.share': 'Teilen',
    'common.loading': 'Laden...',
    'common.error': 'Etwas ist schief gelaufen',
    'common.tryAgain': 'Erneut Versuchen',
    'common.selectLanguage': 'Sprache Auswählen',
  },
  pt: {
    'nav.howItWorks': 'Como Funciona',
    'nav.testimonials': 'Depoimentos',
    'nav.faq': 'FAQ',
    'nav.gift': 'Presentear uma Leitura',
    'nav.getReading': 'Obter Sua Leitura',
    'hero.badge': '✨ Mais de 10.000 Pais de Pets Confiam',
    'hero.title': 'Descubra a',
    'hero.titleHighlight': 'Alma Cósmica',
    'hero.subtitle': 'Desbloqueie os segredos místicos escritos nas estrelas no dia em que seu pet nasceu. Uma jornada astrológica personalizada que revela sua verdadeira natureza, peculiaridades ocultas e o vínculo cósmico que vocês compartilham.',
    'hero.cta': 'Revelar Seu Retrato Cósmico',
    'hero.ctaSubtext': '🌟 Entrega digital instantânea • 100% personalizado',
    'hero.trustpilot': 'Excelente',
    'hero.reviews': 'Baseado em 2.847 avaliações',
    'howItWorks.title': 'Como Funciona',
    'howItWorks.subtitle': 'Três passos simples para desbloquear os segredos cósmicos do seu pet',
    'howItWorks.step1.title': 'Compartilhe os Detalhes',
    'howItWorks.step1.desc': 'Conte-nos sobre seu pet - data de nascimento, traços de personalidade e o que os torna especiais.',
    'howItWorks.step2.title': 'Consultamos as Estrelas',
    'howItWorks.step2.desc': 'Nossos algoritmos cósmicos analisam posições planetárias e criam um perfil astrológico único.',
    'howItWorks.step3.title': 'Receba Seu Relatório',
    'howItWorks.step3.desc': 'Receba um retrato cósmico personalizado lindamente elaborado, entregue instantaneamente no seu e-mail.',
    'testimonials.title': 'O Que Pais de Pets Dizem',
    'testimonials.subtitle': 'Junte-se a milhares que descobriram a verdade cósmica de seus pets',
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Tudo o que você precisa saber sobre a leitura cósmica do seu pet',
    'footer.tagline': 'Revelando o vínculo cósmico entre você e seu amado companheiro.',
    'footer.links': 'Links Rápidos',
    'footer.legal': 'Legal',
    'footer.contact': 'Contato',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.copyright': '© 2024 The Cosmic Pet. Todos os direitos reservados.',
    'intake.letsBegin': 'Vamos Começar Sua Jornada Cósmica',
    'intake.petName': 'Qual é o nome do seu pet?',
    'intake.petNamePlaceholder': 'Digite o nome...',
    'intake.species': 'Que tipo de companheiro é?',
    'intake.breed': 'Qual é a raça de',
    'intake.breedPlaceholder': 'Buscar raças...',
    'intake.gender': '{name} é menino ou menina?',
    'intake.boy': 'Menino',
    'intake.girl': 'Menina',
    'intake.dob': 'Quando {name} nasceu?',
    'intake.dobApprox': 'Data aproximada está ok!',
    'intake.location': 'Onde {name} nasceu?',
    'intake.locationPlaceholder': 'Cidade ou região...',
    'intake.soul': 'O que descreve a alma de {name}?',
    'intake.superpower': 'Qual é o superpoder de {name}?',
    'intake.strangers': 'Como {name} age com estranhos?',
    'intake.email': 'Para onde enviamos o relatório cósmico?',
    'intake.emailPlaceholder': 'seu@email.com',
    'intake.continue': 'Continuar',
    'intake.back': 'Voltar',
    'checkout.title': 'Escolha Seu Pacote Cósmico',
    'checkout.basic': 'Leitura Básica',
    'checkout.premium': 'Leitura Premium',
    'checkout.vip': 'Experiência VIP',
    'checkout.popular': 'Mais Popular',
    'checkout.bestValue': 'Melhor Valor',
    'checkout.unlock': 'Desbloquear Relatório',
    'checkout.addGift': 'Adicionar como Presente',
    'checkout.volumeDiscount': 'Desconto por volume:',
    'report.generating': 'Consultando as Estrelas...',
    'report.generatingDesc': 'O cosmos está se alinhando para revelar a verdadeira natureza de {name}',
    'report.download': 'Baixar PDF',
    'report.share': 'Compartilhar',
    'common.loading': 'Carregando...',
    'common.error': 'Algo deu errado',
    'common.tryAgain': 'Tentar Novamente',
    'common.selectLanguage': 'Selecionar Idioma',
  },
  it: {
    'nav.howItWorks': 'Come Funziona',
    'nav.testimonials': 'Testimonianze',
    'nav.faq': 'FAQ',
    'nav.gift': 'Regala una Lettura',
    'nav.getReading': 'Ottieni la Tua Lettura',
    'hero.badge': '✨ Oltre 10.000 Genitori di Animali si Fidano',
    'hero.title': 'Scopri l\'',
    'hero.titleHighlight': 'Anima Cosmica',
    'hero.subtitle': 'Sblocca i segreti mistici scritti nelle stelle il giorno in cui è nato il tuo animale. Un viaggio astrologico personalizzato che rivela la loro vera natura, le peculiarità nascoste e il legame cosmico che condividete.',
    'hero.cta': 'Rivela il Loro Ritratto Cosmico',
    'hero.ctaSubtext': '🌟 Consegna digitale istantanea • 100% personalizzato',
    'hero.trustpilot': 'Eccellente',
    'hero.reviews': 'Basato su 2.847 recensioni',
    'howItWorks.title': 'Come Funziona',
    'howItWorks.subtitle': 'Tre semplici passaggi per sbloccare i segreti cosmici del tuo animale',
    'howItWorks.step1.title': 'Condividi i Dettagli',
    'howItWorks.step1.desc': 'Parlaci del tuo animale - data di nascita, tratti della personalità e cosa li rende speciali.',
    'howItWorks.step2.title': 'Consultiamo le Stelle',
    'howItWorks.step2.desc': 'I nostri algoritmi cosmici analizzano le posizioni planetarie e creano un profilo astrologico unico.',
    'howItWorks.step3.title': 'Ricevi il Tuo Report',
    'howItWorks.step3.desc': 'Ricevi un ritratto cosmico personalizzato splendidamente realizzato, consegnato istantaneamente nella tua email.',
    'testimonials.title': 'Cosa Dicono i Genitori di Animali',
    'testimonials.subtitle': 'Unisciti a migliaia che hanno scoperto la verità cosmica dei loro animali',
    'faq.title': 'Domande Frequenti',
    'faq.subtitle': 'Tutto ciò che devi sapere sulla lettura cosmica del tuo animale',
    'footer.tagline': 'Rivelando il legame cosmico tra te e il tuo amato compagno.',
    'footer.links': 'Link Rapidi',
    'footer.legal': 'Legale',
    'footer.contact': 'Contatto',
    'footer.privacy': 'Informativa sulla Privacy',
    'footer.terms': 'Termini di Servizio',
    'footer.copyright': '© 2024 The Cosmic Pet. Tutti i diritti riservati.',
    'intake.letsBegin': 'Iniziamo il Tuo Viaggio Cosmico',
    'intake.petName': 'Come si chiama il tuo animale?',
    'intake.petNamePlaceholder': 'Inserisci il nome...',
    'intake.species': 'Che tipo di compagno è?',
    'intake.breed': 'Di che razza è',
    'intake.breedPlaceholder': 'Cerca razze...',
    'intake.gender': '{name} è maschio o femmina?',
    'intake.boy': 'Maschio',
    'intake.girl': 'Femmina',
    'intake.dob': 'Quando è nato/a {name}?',
    'intake.dobApprox': 'Una data approssimativa va bene!',
    'intake.location': 'Dove è nato/a {name}?',
    'intake.locationPlaceholder': 'Città o regione...',
    'intake.soul': 'Cosa descrive l\'anima di {name}?',
    'intake.superpower': 'Qual è il superpotere di {name}?',
    'intake.strangers': 'Come si comporta {name} con gli estranei?',
    'intake.email': 'Dove dobbiamo inviare il report cosmico?',
    'intake.emailPlaceholder': 'tua@email.com',
    'intake.continue': 'Continua',
    'intake.back': 'Indietro',
    'checkout.title': 'Scegli il Tuo Pacchetto Cosmico',
    'checkout.basic': 'Lettura Base',
    'checkout.premium': 'Lettura Premium',
    'checkout.vip': 'Esperienza VIP',
    'checkout.popular': 'Più Popolare',
    'checkout.bestValue': 'Miglior Valore',
    'checkout.unlock': 'Sblocca Report',
    'checkout.addGift': 'Aggiungi come Regalo',
    'checkout.volumeDiscount': 'Sconto volume:',
    'report.generating': 'Consultando le Stelle...',
    'report.generatingDesc': 'Il cosmo si sta allineando per rivelare la vera natura di {name}',
    'report.download': 'Scarica PDF',
    'report.share': 'Condividi',
    'common.loading': 'Caricamento...',
    'common.error': 'Qualcosa è andato storto',
    'common.tryAgain': 'Riprova',
    'common.selectLanguage': 'Seleziona Lingua',
  },
  ja: {
    'nav.howItWorks': '使い方',
    'nav.testimonials': 'お客様の声',
    'nav.faq': 'よくある質問',
    'nav.gift': 'リーディングをギフト',
    'nav.getReading': 'リーディングを取得',
    'hero.badge': '✨ 10,000人以上のペットの親が信頼',
    'hero.title': 'ペットの',
    'hero.titleHighlight': 'コズミックソウル',
    'hero.subtitle': 'ペットが生まれた日に星に書かれた神秘的な秘密を解き明かしましょう。真の本性、隠された癖、そしてあなたが共有する宇宙的な絆を明らかにするパーソナライズされた占星術の旅。',
    'hero.cta': 'コズミックポートレートを明らかに',
    'hero.ctaSubtext': '🌟 即時デジタル配信 • 100%パーソナライズ',
    'hero.trustpilot': '優秀',
    'hero.reviews': '2,847件のレビューに基づく',
    'howItWorks.title': '使い方',
    'howItWorks.subtitle': 'ペットの宇宙の秘密を解き明かす3つの簡単なステップ',
    'howItWorks.step1.title': '詳細を共有',
    'howItWorks.step1.desc': 'ペットについて教えてください - 生年月日、性格特性、特別な点。',
    'howItWorks.step2.title': '星に相談',
    'howItWorks.step2.desc': '私たちのコズミックアルゴリズムが惑星の位置を分析し、ユニークな占星術プロファイルを作成します。',
    'howItWorks.step3.title': 'レポートを受け取る',
    'howItWorks.step3.desc': '美しく作成されたパーソナライズされたコズミックポートレートを即座にメールで受け取ります。',
    'testimonials.title': 'ペットの親の声',
    'testimonials.subtitle': 'ペットの宇宙的真実を発見した何千人もの仲間に加わりましょう',
    'faq.title': 'よくある質問',
    'faq.subtitle': 'ペットのコズミックリーディングについて知っておくべきこと',
    'footer.tagline': 'あなたと愛するコンパニオンの間の宇宙的な絆を明らかにします。',
    'footer.links': 'クイックリンク',
    'footer.legal': '法的情報',
    'footer.contact': 'お問い合わせ',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.copyright': '© 2024 The Cosmic Pet. 全著作権所有。',
    'intake.letsBegin': 'コズミックジャーニーを始めましょう',
    'intake.petName': 'ペットの名前は？',
    'intake.petNamePlaceholder': '名前を入力...',
    'intake.species': 'どんな種類のコンパニオン？',
    'intake.breed': '品種は',
    'intake.breedPlaceholder': '品種を検索...',
    'intake.gender': '{name}は男の子？女の子？',
    'intake.boy': '男の子',
    'intake.girl': '女の子',
    'intake.dob': '{name}の誕生日は？',
    'intake.dobApprox': 'おおよその日付でOK！',
    'intake.location': '{name}の出生地は？',
    'intake.locationPlaceholder': '市区町村...',
    'intake.soul': '{name}の魂を表すものは？',
    'intake.superpower': '{name}のスーパーパワーは？',
    'intake.strangers': '{name}は知らない人にどう接する？',
    'intake.email': 'コズミックレポートの送信先は？',
    'intake.emailPlaceholder': 'your@email.com',
    'intake.continue': '続ける',
    'intake.back': '戻る',
    'checkout.title': 'コズミックパッケージを選択',
    'checkout.basic': 'ベーシックリーディング',
    'checkout.premium': 'プレミアムリーディング',
    'checkout.vip': 'VIP体験',
    'checkout.popular': '最も人気',
    'checkout.bestValue': '最高の価値',
    'checkout.unlock': 'レポートをアンロック',
    'checkout.addGift': 'ギフトとして追加',
    'checkout.volumeDiscount': 'ボリューム割引:',
    'report.generating': '星に相談中...',
    'report.generatingDesc': '宇宙が{name}の本当の姿を明らかにするために整列しています',
    'report.download': 'PDFダウンロード',
    'report.share': 'シェア',
    'common.loading': '読み込み中...',
    'common.error': '問題が発生しました',
    'common.tryAgain': '再試行',
    'common.selectLanguage': '言語を選択',
  },
  zh: {
    'nav.howItWorks': '如何运作',
    'nav.testimonials': '用户评价',
    'nav.faq': '常见问题',
    'nav.gift': '赠送阅读',
    'nav.getReading': '获取您的阅读',
    'hero.badge': '✨ 超过10,000位宠物家长信赖',
    'hero.title': '发现您宠物的',
    'hero.titleHighlight': '宇宙灵魂',
    'hero.subtitle': '解锁您宠物出生那天写在星星中的神秘秘密。一段个性化的占星之旅，揭示它们的真实本性、隐藏的怪癖以及你们共享的宇宙纽带。',
    'hero.cta': '揭示它们的宇宙肖像',
    'hero.ctaSubtext': '🌟 即时数字交付 • 100%个性化',
    'hero.trustpilot': '优秀',
    'hero.reviews': '基于2,847条评论',
    'howItWorks.title': '如何运作',
    'howItWorks.subtitle': '三个简单步骤解锁您宠物的宇宙秘密',
    'howItWorks.step1.title': '分享详情',
    'howItWorks.step1.desc': '告诉我们您的宠物 - 出生日期、性格特征以及是什么让它们特别。',
    'howItWorks.step2.title': '我们咨询星星',
    'howItWorks.step2.desc': '我们的宇宙算法分析行星位置并创建独特的占星档案。',
    'howItWorks.step3.title': '接收您的报告',
    'howItWorks.step3.desc': '获得精美制作的个性化宇宙肖像，即时发送到您的邮箱。',
    'testimonials.title': '宠物家长怎么说',
    'testimonials.subtitle': '加入数千位发现了宠物宇宙真相的人',
    'faq.title': '常见问题',
    'faq.subtitle': '关于宠物宇宙阅读您需要知道的一切',
    'footer.tagline': '揭示您与心爱伙伴之间的宇宙纽带。',
    'footer.links': '快速链接',
    'footer.legal': '法律信息',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.copyright': '© 2024 The Cosmic Pet. 保留所有权利。',
    'intake.letsBegin': '开始您的宇宙之旅',
    'intake.petName': '您宠物的名字是？',
    'intake.petNamePlaceholder': '输入名字...',
    'intake.species': '它是什么类型的伙伴？',
    'intake.breed': '的品种是什么',
    'intake.breedPlaceholder': '搜索品种...',
    'intake.gender': '{name}是男孩还是女孩？',
    'intake.boy': '男孩',
    'intake.girl': '女孩',
    'intake.dob': '{name}什么时候出生的？',
    'intake.dobApprox': '大概日期就可以！',
    'intake.location': '{name}在哪里出生？',
    'intake.locationPlaceholder': '城市或地区...',
    'intake.soul': '什么描述{name}的灵魂？',
    'intake.superpower': '{name}的超能力是什么？',
    'intake.strangers': '{name}对陌生人的反应如何？',
    'intake.email': '宇宙报告发送到哪里？',
    'intake.emailPlaceholder': '您的@email.com',
    'intake.continue': '继续',
    'intake.back': '返回',
    'checkout.title': '选择您的宇宙套餐',
    'checkout.basic': '基础阅读',
    'checkout.premium': '高级阅读',
    'checkout.vip': 'VIP体验',
    'checkout.popular': '最受欢迎',
    'checkout.bestValue': '最佳价值',
    'checkout.unlock': '解锁报告',
    'checkout.addGift': '作为礼物添加',
    'checkout.volumeDiscount': '批量折扣:',
    'report.generating': '咨询星星中...',
    'report.generatingDesc': '宇宙正在排列以揭示{name}的真实本性',
    'report.download': '下载PDF',
    'report.share': '分享',
    'common.loading': '加载中...',
    'common.error': '出了点问题',
    'common.tryAgain': '重试',
    'common.selectLanguage': '选择语言',
  },
  ko: {
    'nav.howItWorks': '작동 방식',
    'nav.testimonials': '후기',
    'nav.faq': 'FAQ',
    'nav.gift': '리딩 선물하기',
    'nav.getReading': '리딩 받기',
    'hero.badge': '✨ 10,000명 이상의 반려동물 부모가 신뢰',
    'hero.title': '반려동물의',
    'hero.titleHighlight': '코스믹 소울',
    'hero.subtitle': '반려동물이 태어난 날 별에 쓰여진 신비로운 비밀을 풀어보세요. 그들의 진정한 본성, 숨겨진 특이점, 그리고 당신이 공유하는 우주적 유대를 밝혀주는 개인화된 점성술 여행.',
    'hero.cta': '코스믹 초상화 공개',
    'hero.ctaSubtext': '🌟 즉시 디지털 전달 • 100% 맞춤화',
    'hero.trustpilot': '우수',
    'hero.reviews': '2,847개의 리뷰 기준',
    'howItWorks.title': '작동 방식',
    'howItWorks.subtitle': '반려동물의 우주 비밀을 풀어주는 세 가지 간단한 단계',
    'howItWorks.step1.title': '세부 정보 공유',
    'howItWorks.step1.desc': '반려동물에 대해 알려주세요 - 생년월일, 성격 특성, 그리고 특별한 점.',
    'howItWorks.step2.title': '별에게 상담',
    'howItWorks.step2.desc': '우리의 코스믹 알고리즘이 행성 위치를 분석하고 고유한 점성술 프로필을 만듭니다.',
    'howItWorks.step3.title': '리포트 받기',
    'howItWorks.step3.desc': '아름답게 만들어진 개인화된 코스믹 초상화를 이메일로 즉시 받아보세요.',
    'testimonials.title': '반려동물 부모들의 말',
    'testimonials.subtitle': '반려동물의 우주적 진실을 발견한 수천 명의 사람들과 함께하세요',
    'faq.title': '자주 묻는 질문',
    'faq.subtitle': '반려동물의 코스믹 리딩에 대해 알아야 할 모든 것',
    'footer.tagline': '당신과 사랑하는 반려동물 사이의 우주적 유대를 밝힙니다.',
    'footer.links': '빠른 링크',
    'footer.legal': '법적 정보',
    'footer.contact': '연락처',
    'footer.privacy': '개인정보 보호정책',
    'footer.terms': '서비스 약관',
    'footer.copyright': '© 2024 The Cosmic Pet. 모든 권리 보유.',
    'intake.letsBegin': '코스믹 여정을 시작합시다',
    'intake.petName': '반려동물의 이름은?',
    'intake.petNamePlaceholder': '이름을 입력하세요...',
    'intake.species': '어떤 종류의 반려동물인가요?',
    'intake.breed': '의 품종은',
    'intake.breedPlaceholder': '품종 검색...',
    'intake.gender': '{name}은 남자아이인가요 여자아이인가요?',
    'intake.boy': '남자아이',
    'intake.girl': '여자아이',
    'intake.dob': '{name}의 생년월일은?',
    'intake.dobApprox': '대략적인 날짜도 괜찮아요!',
    'intake.location': '{name}은 어디서 태어났나요?',
    'intake.locationPlaceholder': '도시 또는 지역...',
    'intake.soul': '{name}의 영혼을 설명하는 것은?',
    'intake.superpower': '{name}의 슈퍼파워는?',
    'intake.strangers': '{name}은 낯선 사람에게 어떻게 행동하나요?',
    'intake.email': '코스믹 리포트를 어디로 보낼까요?',
    'intake.emailPlaceholder': '당신의@email.com',
    'intake.continue': '계속',
    'intake.back': '뒤로',
    'checkout.title': '코스믹 패키지 선택',
    'checkout.basic': '기본 리딩',
    'checkout.premium': '프리미엄 리딩',
    'checkout.vip': 'VIP 경험',
    'checkout.popular': '가장 인기',
    'checkout.bestValue': '최고 가치',
    'checkout.unlock': '리포트 잠금 해제',
    'checkout.addGift': '선물로 추가',
    'checkout.volumeDiscount': '대량 할인:',
    'report.generating': '별에게 상담 중...',
    'report.generatingDesc': '우주가 {name}의 진정한 본성을 밝히기 위해 정렬하고 있습니다',
    'report.download': 'PDF 다운로드',
    'report.share': '공유',
    'common.loading': '로딩 중...',
    'common.error': '문제가 발생했습니다',
    'common.tryAgain': '다시 시도',
    'common.selectLanguage': '언어 선택',
  },
  nl: {
    'nav.howItWorks': 'Hoe Het Werkt',
    'nav.testimonials': 'Getuigenissen',
    'nav.faq': 'FAQ',
    'nav.gift': 'Geef een Reading Cadeau',
    'nav.getReading': 'Krijg Je Reading',
    'hero.badge': '✨ Vertrouwd door 10.000+ Huisdier Ouders',
    'hero.title': 'Ontdek de',
    'hero.titleHighlight': 'Kosmische Ziel',
    'hero.subtitle': 'Ontgrendel de mystieke geheimen geschreven in de sterren op de dag dat je huisdier werd geboren. Een gepersonaliseerde astrologische reis die hun ware aard, verborgen eigenaardigheden en de kosmische band die jullie delen onthult.',
    'hero.cta': 'Onthul Hun Kosmisch Portret',
    'hero.ctaSubtext': '🌟 Directe digitale levering • 100% gepersonaliseerd',
    'hero.trustpilot': 'Uitstekend',
    'hero.reviews': 'Gebaseerd op 2.847 beoordelingen',
    'howItWorks.title': 'Hoe Het Werkt',
    'howItWorks.subtitle': 'Drie eenvoudige stappen om de kosmische geheimen van je huisdier te ontgrendelen',
    'howItWorks.step1.title': 'Deel Hun Details',
    'howItWorks.step1.desc': 'Vertel ons over je huisdier - geboortedatum, persoonlijkheidskenmerken en wat hen speciaal maakt.',
    'howItWorks.step2.title': 'Wij Raadplegen de Sterren',
    'howItWorks.step2.desc': 'Onze kosmische algoritmen analyseren planetaire posities en creëren een uniek astrologisch profiel.',
    'howItWorks.step3.title': 'Ontvang Je Rapport',
    'howItWorks.step3.desc': 'Ontvang een prachtig gemaakt, gepersonaliseerd kosmisch portret, direct in je inbox.',
    'testimonials.title': 'Wat Huisdier Ouders Zeggen',
    'testimonials.subtitle': 'Sluit je aan bij duizenden die de kosmische waarheid van hun huisdier hebben ontdekt',
    'faq.title': 'Veelgestelde Vragen',
    'faq.subtitle': 'Alles wat je moet weten over de kosmische reading van je huisdier',
    'footer.tagline': 'De kosmische band tussen jou en je geliefde metgezel onthullen.',
    'footer.links': 'Snelle Links',
    'footer.legal': 'Juridisch',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'footer.copyright': '© 2024 The Cosmic Pet. Alle rechten voorbehouden.',
    'intake.letsBegin': 'Laten We Je Kosmische Reis Beginnen',
    'intake.petName': 'Wat is de naam van je huisdier?',
    'intake.petNamePlaceholder': 'Voer naam in...',
    'intake.species': 'Wat voor soort metgezel is het?',
    'intake.breed': 'Wat is het ras van',
    'intake.breedPlaceholder': 'Zoek rassen...',
    'intake.gender': 'Is {name} een jongen of meisje?',
    'intake.boy': 'Jongen',
    'intake.girl': 'Meisje',
    'intake.dob': 'Wanneer is {name} geboren?',
    'intake.dobApprox': 'Een geschatte datum is prima!',
    'intake.location': 'Waar is {name} geboren?',
    'intake.locationPlaceholder': 'Stad of regio...',
    'intake.soul': 'Wat beschrijft de ziel van {name}?',
    'intake.superpower': 'Wat is de superkracht van {name}?',
    'intake.strangers': 'Hoe gedraagt {name} zich bij vreemden?',
    'intake.email': 'Waar moeten we het kosmische rapport naartoe sturen?',
    'intake.emailPlaceholder': 'jouw@email.com',
    'intake.continue': 'Doorgaan',
    'intake.back': 'Terug',
    'checkout.title': 'Kies Je Kosmische Pakket',
    'checkout.basic': 'Basis Reading',
    'checkout.premium': 'Premium Reading',
    'checkout.vip': 'VIP Ervaring',
    'checkout.popular': 'Meest Populair',
    'checkout.bestValue': 'Beste Waarde',
    'checkout.unlock': 'Rapport Ontgrendelen',
    'checkout.addGift': 'Toevoegen als Cadeau',
    'checkout.volumeDiscount': 'Volume korting:',
    'report.generating': 'De Sterren Raadplegen...',
    'report.generatingDesc': 'De kosmos lijnt zich uit om de ware aard van {name} te onthullen',
    'report.download': 'PDF Downloaden',
    'report.share': 'Delen',
    'common.loading': 'Laden...',
    'common.error': 'Er ging iets mis',
    'common.tryAgain': 'Opnieuw Proberen',
    'common.selectLanguage': 'Selecteer Taal',
  },
  ru: {
    'nav.howItWorks': 'Как Это Работает',
    'nav.testimonials': 'Отзывы',
    'nav.faq': 'FAQ',
    'nav.gift': 'Подарить Чтение',
    'nav.getReading': 'Получить Чтение',
    'hero.badge': '✨ Более 10 000 Владельцев Питомцев Доверяют',
    'hero.title': 'Откройте',
    'hero.titleHighlight': 'Космическую Душу',
    'hero.subtitle': 'Раскройте мистические секреты, записанные в звёздах в день рождения вашего питомца. Персонализированное астрологическое путешествие, которое раскрывает их истинную природу, скрытые причуды и космическую связь, которую вы разделяете.',
    'hero.cta': 'Раскрыть Их Космический Портрет',
    'hero.ctaSubtext': '🌟 Мгновенная цифровая доставка • 100% персонализировано',
    'hero.trustpilot': 'Отлично',
    'hero.reviews': 'На основе 2 847 отзывов',
    'howItWorks.title': 'Как Это Работает',
    'howItWorks.subtitle': 'Три простых шага, чтобы раскрыть космические секреты вашего питомца',
    'howItWorks.step1.title': 'Поделитесь Деталями',
    'howItWorks.step1.desc': 'Расскажите нам о вашем питомце - дата рождения, черты характера и что делает их особенными.',
    'howItWorks.step2.title': 'Мы Консультируемся со Звёздами',
    'howItWorks.step2.desc': 'Наши космические алгоритмы анализируют положения планет и создают уникальный астрологический профиль.',
    'howItWorks.step3.title': 'Получите Отчёт',
    'howItWorks.step3.desc': 'Получите красиво оформленный персонализированный космический портрет, доставленный мгновенно на вашу почту.',
    'testimonials.title': 'Что Говорят Владельцы Питомцев',
    'testimonials.subtitle': 'Присоединяйтесь к тысячам, кто открыл космическую истину своих питомцев',
    'faq.title': 'Часто Задаваемые Вопросы',
    'faq.subtitle': 'Всё, что вам нужно знать о космическом чтении вашего питомца',
    'footer.tagline': 'Раскрывая космическую связь между вами и вашим любимым компаньоном.',
    'footer.links': 'Быстрые Ссылки',
    'footer.legal': 'Правовая Информация',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Политика Конфиденциальности',
    'footer.terms': 'Условия Использования',
    'footer.copyright': '© 2024 The Cosmic Pet. Все права защищены.',
    'intake.letsBegin': 'Начнём Ваше Космическое Путешествие',
    'intake.petName': 'Как зовут вашего питомца?',
    'intake.petNamePlaceholder': 'Введите имя...',
    'intake.species': 'Какой это тип компаньона?',
    'intake.breed': 'Какой породы',
    'intake.breedPlaceholder': 'Поиск пород...',
    'intake.gender': '{name} мальчик или девочка?',
    'intake.boy': 'Мальчик',
    'intake.girl': 'Девочка',
    'intake.dob': 'Когда родился {name}?',
    'intake.dobApprox': 'Приблизительная дата подойдёт!',
    'intake.location': 'Где родился {name}?',
    'intake.locationPlaceholder': 'Город или регион...',
    'intake.soul': 'Что описывает душу {name}?',
    'intake.superpower': 'Какая суперспособность у {name}?',
    'intake.strangers': 'Как {name} ведёт себя с незнакомцами?',
    'intake.email': 'Куда отправить космический отчёт?',
    'intake.emailPlaceholder': 'ваш@email.com',
    'intake.continue': 'Продолжить',
    'intake.back': 'Назад',
    'checkout.title': 'Выберите Ваш Космический Пакет',
    'checkout.basic': 'Базовое Чтение',
    'checkout.premium': 'Премиум Чтение',
    'checkout.vip': 'VIP Опыт',
    'checkout.popular': 'Самый Популярный',
    'checkout.bestValue': 'Лучшая Цена',
    'checkout.unlock': 'Разблокировать Отчёт',
    'checkout.addGift': 'Добавить как Подарок',
    'checkout.volumeDiscount': 'Скидка за объём:',
    'report.generating': 'Консультируемся со Звёздами...',
    'report.generatingDesc': 'Космос выстраивается, чтобы раскрыть истинную природу {name}',
    'report.download': 'Скачать PDF',
    'report.share': 'Поделиться',
    'common.loading': 'Загрузка...',
    'common.error': 'Что-то пошло не так',
    'common.tryAgain': 'Попробовать Снова',
    'common.selectLanguage': 'Выбрать Язык',
  },
  ar: {
    'nav.howItWorks': 'كيف يعمل',
    'nav.testimonials': 'الشهادات',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.gift': 'أهدِ قراءة',
    'nav.getReading': 'احصل على قراءتك',
    'hero.badge': '✨ موثوق من قبل أكثر من 10,000 من أولياء الحيوانات الأليفة',
    'hero.title': 'اكتشف',
    'hero.titleHighlight': 'الروح الكونية',
    'hero.subtitle': 'افتح الأسرار الغامضة المكتوبة في النجوم يوم ولادة حيوانك الأليف. رحلة فلكية مخصصة تكشف طبيعتهم الحقيقية وصفاتهم الخفية والرابط الكوني الذي تتشاركونه.',
    'hero.cta': 'اكشف صورتهم الكونية',
    'hero.ctaSubtext': '🌟 توصيل رقمي فوري • مخصص 100%',
    'hero.trustpilot': 'ممتاز',
    'hero.reviews': 'بناءً على 2,847 تقييم',
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'ثلاث خطوات بسيطة لفتح أسرار حيوانك الأليف الكونية',
    'howItWorks.step1.title': 'شارك تفاصيلهم',
    'howItWorks.step1.desc': 'أخبرنا عن حيوانك الأليف - تاريخ الميلاد، سمات الشخصية، وما يجعلهم مميزين.',
    'howItWorks.step2.title': 'نستشير النجوم',
    'howItWorks.step2.desc': 'خوارزمياتنا الكونية تحلل مواقع الكواكب وتنشئ ملفًا فلكيًا فريدًا.',
    'howItWorks.step3.title': 'استلم تقريرك',
    'howItWorks.step3.desc': 'احصل على صورة كونية مخصصة مصممة بشكل جميل، تُسلم فورًا إلى بريدك الإلكتروني.',
    'testimonials.title': 'ماذا يقول أولياء الحيوانات الأليفة',
    'testimonials.subtitle': 'انضم إلى الآلاف الذين اكتشفوا الحقيقة الكونية لحيواناتهم الأليفة',
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'كل ما تحتاج معرفته عن القراءة الكونية لحيوانك الأليف',
    'footer.tagline': 'كشف الرابط الكوني بينك وبين رفيقك المحبوب.',
    'footer.links': 'روابط سريعة',
    'footer.legal': 'قانوني',
    'footer.contact': 'اتصل',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.copyright': '© 2024 The Cosmic Pet. جميع الحقوق محفوظة.',
    'intake.letsBegin': 'لنبدأ رحلتك الكونية',
    'intake.petName': 'ما اسم حيوانك الأليف؟',
    'intake.petNamePlaceholder': 'أدخل الاسم...',
    'intake.species': 'ما نوع الرفيق؟',
    'intake.breed': 'ما سلالة',
    'intake.breedPlaceholder': 'ابحث عن السلالات...',
    'intake.gender': 'هل {name} ذكر أم أنثى؟',
    'intake.boy': 'ذكر',
    'intake.girl': 'أنثى',
    'intake.dob': 'متى ولد {name}؟',
    'intake.dobApprox': 'التاريخ التقريبي مقبول!',
    'intake.location': 'أين ولد {name}؟',
    'intake.locationPlaceholder': 'المدينة أو المنطقة...',
    'intake.soul': 'ما الذي يصف روح {name}؟',
    'intake.superpower': 'ما هي القوة الخارقة لـ {name}؟',
    'intake.strangers': 'كيف يتصرف {name} مع الغرباء؟',
    'intake.email': 'أين نرسل التقرير الكوني؟',
    'intake.emailPlaceholder': 'بريدك@email.com',
    'intake.continue': 'متابعة',
    'intake.back': 'رجوع',
    'checkout.title': 'اختر باقتك الكونية',
    'checkout.basic': 'القراءة الأساسية',
    'checkout.premium': 'القراءة المميزة',
    'checkout.vip': 'تجربة VIP',
    'checkout.popular': 'الأكثر شعبية',
    'checkout.bestValue': 'أفضل قيمة',
    'checkout.unlock': 'فتح التقرير',
    'checkout.addGift': 'إضافة كهدية',
    'checkout.volumeDiscount': 'خصم الكمية:',
    'report.generating': 'استشارة النجوم...',
    'report.generatingDesc': 'الكون يصطف ليكشف طبيعة {name} الحقيقية',
    'report.download': 'تحميل PDF',
    'report.share': 'مشاركة',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ ما',
    'common.tryAgain': 'حاول مرة أخرى',
    'common.selectLanguage': 'اختر اللغة',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('cosmicPetLanguage');
    if (saved && translations[saved as Language]) {
      return saved as Language;
    }
    // Try to detect browser language
    const browserLang = navigator.language.split('-')[0] as Language;
    if (translations[browserLang]) {
      return browserLang;
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('cosmicPetLanguage', lang);
    // Set document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
