-- Create blog_topics table for the keyword queue
CREATE TABLE public.blog_topics (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  topic TEXT NOT NULL,
  species TEXT NOT NULL DEFAULT 'dog',
  category TEXT NOT NULL DEFAULT 'behavior',
  priority INTEGER DEFAULT 0,
  is_used BOOLEAN DEFAULT false,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.blog_topics ENABLE ROW LEVEL SECURITY;

-- Service role access only
CREATE POLICY "Service role only for blog topics"
  ON public.blog_topics
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Index for fetching unused topics
CREATE INDEX idx_blog_topics_unused ON public.blog_topics(is_used, priority DESC);

-- Insert 100 high-value SEO keywords
INSERT INTO public.blog_topics (topic, species, category, priority) VALUES
-- Dog behavior (50 topics)
('why does my dog eat grass', 'dog', 'behavior', 100),
('why does my dog lick me so much', 'dog', 'behavior', 99),
('why does my dog follow me everywhere', 'dog', 'behavior', 98),
('why does my dog stare at me', 'dog', 'behavior', 97),
('why does my dog shake', 'dog', 'behavior', 96),
('why does my dog yawn when I pet him', 'dog', 'behavior', 95),
('why does my dog sleep on my feet', 'dog', 'behavior', 94),
('why does my dog tilt his head', 'dog', 'behavior', 93),
('why does my dog howl at sirens', 'dog', 'behavior', 92),
('why does my dog bark at nothing', 'dog', 'behavior', 91),
('why does my dog dig holes in the yard', 'dog', 'behavior', 90),
('why does my dog roll in smelly things', 'dog', 'behavior', 89),
('why does my dog hide treats', 'dog', 'behavior', 88),
('why does my dog chase his tail', 'dog', 'behavior', 87),
('why does my dog pant when not hot', 'dog', 'behavior', 86),
('why does my dog sleep with his tongue out', 'dog', 'behavior', 85),
('why does my dog snore', 'dog', 'behavior', 84),
('why does my dog kick after pooping', 'dog', 'behavior', 83),
('why does my dog spin before lying down', 'dog', 'behavior', 82),
('why does my dog lean on me', 'dog', 'behavior', 81),
('why does my dog put his paw on me', 'dog', 'behavior', 80),
('why does my dog sigh', 'dog', 'behavior', 79),
('why does my dog stretch when he sees me', 'dog', 'behavior', 78),
('why does my dog bring me his toys', 'dog', 'behavior', 77),
('why does my dog sneeze when playing', 'dog', 'behavior', 76),
('why does my dog sleep belly up', 'dog', 'behavior', 75),
('why does my dog whine at night', 'dog', 'behavior', 74),
('why does my dog eat poop', 'dog', 'behavior', 73),
('why does my dog jump on people', 'dog', 'behavior', 72),
('why does my dog hump things', 'dog', 'behavior', 71),
('why does my dog scratch the floor before lying down', 'dog', 'behavior', 70),
('why does my dog like to be petted', 'dog', 'behavior', 69),
('why does my dog wag his tail in his sleep', 'dog', 'behavior', 68),
('why does my dog growl when I hug him', 'dog', 'behavior', 67),
('why does my dog lick his paws', 'dog', 'behavior', 66),
('why does my dog hate baths', 'dog', 'behavior', 65),
('why does my dog love car rides', 'dog', 'behavior', 64),
('why does my dog get the zoomies', 'dog', 'behavior', 63),
('why does my dog sleep so much', 'dog', 'behavior', 62),
('why does my dog sniff other dogs', 'dog', 'behavior', 61),
('why does my dog cry when I leave', 'dog', 'behavior', 60),
('why does my dog bark at the mailman', 'dog', 'behavior', 59),
('why does my dog hide under the bed', 'dog', 'behavior', 58),
('why does my dog steal socks', 'dog', 'behavior', 57),
('why does my dog lick my face', 'dog', 'behavior', 56),
('why does my dog hate the vacuum', 'dog', 'behavior', 55),
('why does my dog chew on everything', 'dog', 'behavior', 54),
('why does my dog protect me', 'dog', 'behavior', 53),
('why does my dog love belly rubs', 'dog', 'behavior', 52),
('why does my dog run away', 'dog', 'behavior', 51),
-- Cat behavior (50 topics)
('why does my cat knead', 'cat', 'behavior', 100),
('why does my cat stare at me', 'cat', 'behavior', 99),
('why does my cat purr', 'cat', 'behavior', 98),
('why does my cat meow at night', 'cat', 'behavior', 97),
('why does my cat follow me to the bathroom', 'cat', 'behavior', 96),
('why does my cat bite me', 'cat', 'behavior', 95),
('why does my cat knock things off tables', 'cat', 'behavior', 94),
('why does my cat bring me dead animals', 'cat', 'behavior', 93),
('why does my cat sleep on my head', 'cat', 'behavior', 92),
('why does my cat lick me', 'cat', 'behavior', 91),
('why does my cat show me her belly', 'cat', 'behavior', 90),
('why does my cat chirp at birds', 'cat', 'behavior', 89),
('why does my cat hiss', 'cat', 'behavior', 88),
('why does my cat scratch furniture', 'cat', 'behavior', 87),
('why does my cat love boxes', 'cat', 'behavior', 86),
('why does my cat sit on my laptop', 'cat', 'behavior', 85),
('why does my cat groom me', 'cat', 'behavior', 84),
('why does my cat hide', 'cat', 'behavior', 83),
('why does my cat run around at 3am', 'cat', 'behavior', 82),
('why does my cat drool', 'cat', 'behavior', 81),
('why does my cat sleep so much', 'cat', 'behavior', 80),
('why does my cat headbutt me', 'cat', 'behavior', 79),
('why does my cat eat plastic', 'cat', 'behavior', 78),
('why does my cat drink from the faucet', 'cat', 'behavior', 77),
('why does my cat sleep in the sink', 'cat', 'behavior', 76),
('why does my cat make biscuits on me', 'cat', 'behavior', 75),
('why does my cat chatter', 'cat', 'behavior', 74),
('why does my cat ignore me', 'cat', 'behavior', 73),
('why does my cat rub against my legs', 'cat', 'behavior', 72),
('why does my cat wag her tail', 'cat', 'behavior', 71),
('why does my cat hate water', 'cat', 'behavior', 70),
('why does my cat cover her food', 'cat', 'behavior', 69),
('why does my cat eat grass', 'cat', 'behavior', 68),
('why does my cat sleep curled up', 'cat', 'behavior', 67),
('why does my cat watch me sleep', 'cat', 'behavior', 66),
('why does my cat attack my ankles', 'cat', 'behavior', 65),
('why does my cat hate closed doors', 'cat', 'behavior', 64),
('why does my cat love catnip', 'cat', 'behavior', 63),
('why does my cat suckle blankets', 'cat', 'behavior', 62),
('why does my cat arch her back', 'cat', 'behavior', 61),
('why does my cat puff up her tail', 'cat', 'behavior', 60),
('why does my cat slow blink at me', 'cat', 'behavior', 59),
('why does my cat bury her poop', 'cat', 'behavior', 58),
('why does my cat yowl', 'cat', 'behavior', 57),
('why does my cat like high places', 'cat', 'behavior', 56),
('why does my cat play with her water', 'cat', 'behavior', 55),
('why does my cat bring me toys', 'cat', 'behavior', 54),
('why does my cat sleep with me', 'cat', 'behavior', 53),
('why does my cat hate belly rubs', 'cat', 'behavior', 52),
('why does my cat wake me up early', 'cat', 'behavior', 51);