-- Phase 6 — viewer-token column for the customer-facing /reading/<token> page.
--
-- Token = HMAC-SHA256(job.id + ":" + customer_email, READING_TOKEN_SECRET)
-- truncated to 32 base64url chars. Generated by the Phase 4 webhook handler
-- at insert-time (see api/_lib/readingToken.ts). Customer never sees the
-- jobId or email in the URL — they hit https://littlesouls.app/reading/<token>,
-- the API resolves the row by token, and serves the reading content from
-- public.pet_reports via the existing CosmicReportViewer.
--
-- UNIQUE so the lookup is a single index seek. NULL-allowed because rows
-- inserted before this migration (none in production yet, but defensive)
-- and the reconciliation cron need to backfill before erroring.
--
-- Source of truth:
--   • [[research-2026-05-04-soul-reading-fulfilment]] §5.1 (URL pattern + token)
--   • [[launch-plan-2026-05-05]] Phase 6 (viewer page)

ALTER TABLE public.soul_reading_jobs
  ADD COLUMN IF NOT EXISTS viewer_token text UNIQUE;

CREATE INDEX IF NOT EXISTS soul_reading_jobs_token_idx
  ON public.soul_reading_jobs (viewer_token);

COMMENT ON COLUMN public.soul_reading_jobs.viewer_token IS
  'URL-safe HMAC-derived token for the customer viewer page (/reading/<token>). Generated by the webhook handler via api/_lib/readingToken.ts at insert time. UNIQUE — base64url, 32 chars.';
