-- Seed Months 2 and 3 of editorial calendar (24 posts)
-- Source of truth: /docs/phase2-editorial-calendar.md
-- Month 2 = May 2026 (puppy season), Month 3 = June 2026 (memorial gentle peak)

INSERT INTO public.blog_topics (
  topic, species, category, priority, cluster, is_pillar, author_slug,
  tags, scheduled_for, cta_url, working_title, target_keyword
) VALUES
-- ========== Month 2 (May 2026) ==========
('may dog personality', 'dog', 'birthday', 189, 'C', false, 'callum-hayes',
  ARRAY['birthday','dog','may','taurus','gemini'], '2026-05-18', '/checkout',
  'Dog Born in May: Personality Traits, Quirks & What to Expect',
  'dog born in may personality'),
('puppy first birthday', 'dog', 'birthday', 188, 'C', false, 'elena-whitaker',
  ARRAY['birthday','puppy','bonding'], '2026-05-20', '/checkout',
  'Puppy''s First Birthday: How to Build a Cosmic Bond From Day One',
  'puppy first birthday'),
('gemini dog personality', 'dog', 'pet-astrology', 187, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','gemini'], '2026-05-22', '/checkout',
  'Gemini Dogs: The Social Chatterboxes',
  'gemini dog personality'),
('cat zodiac compatibility', 'cat', 'pet-astrology', 186, 'A', false, 'maggie-oshea',
  ARRAY['zodiac','cat','compatibility'], '2026-05-25', '/checkout',
  'Cat Zodiac Compatibility: Which Signs Make the Best Housemates',
  'cat zodiac compatibility'),
('why dog follows me', 'dog', 'soulspeak', 185, 'G', false, 'elena-whitaker',
  ARRAY['behavior','dog','soulspeak'], '2026-05-27', '/soul-chat',
  'Why Does My Dog Follow Me Everywhere? Behavior + Birth Chart',
  'why does my dog follow me everywhere'),
('cancer dog personality', 'dog', 'pet-astrology', 184, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','cancer'], '2026-05-29', '/checkout',
  'The Cancer Dog: Loyal, Sensitive, Deeply Bonded',
  'cancer dog personality'),
('zodiac puppy names', 'dog', 'breed-personality', 183, 'B', false, 'river-callahan',
  ARRAY['naming','puppy','zodiac'], '2026-06-01', '/checkout',
  'New Puppy Name Ideas by Zodiac Sign',
  'zodiac puppy names'),
('cat birth month', 'cat', 'birthday', 182, 'C', false, 'maggie-oshea',
  ARRAY['birthday','cat','month'], '2026-06-03', '/checkout',
  'How Your Cat''s Birth Month Shapes Their Personality',
  'cat birth month personality'),
('do pets know death', 'dog', 'memorial', 181, 'D', false, 'rowan-sterling',
  ARRAY['memorial','grief','animal-intuition'], '2026-06-05', '/soul-chat',
  'What Animals Know About Death: Lessons from Vets and Shamans',
  'do pets know death'),
('leo dog personality', 'dog', 'pet-astrology', 180, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','leo'], '2026-06-08', '/checkout',
  'Leo Dogs: The Main Character Energy Breed',
  'leo dog personality'),
('new puppy checklist', 'dog', 'birthday', 179, 'C', false, 'elena-whitaker',
  ARRAY['puppy','checklist','cosmic'], '2026-06-10', '/checkout',
  'First-Time Puppy Parent Checklist (Cosmic Edition)',
  'new puppy checklist'),
('rescue dog personality', 'dog', 'breed-personality', 178, 'B', false, 'callum-hayes',
  ARRAY['breed','rescue','archetypes'], '2026-06-12', '/checkout',
  'The 7 Rescue Dog Archetypes (And Their Zodiac Match)',
  'rescue dog personality'),

-- ========== Month 3 (June 2026) ==========
('june dog personality', 'dog', 'birthday', 177, 'C', false, 'callum-hayes',
  ARRAY['birthday','dog','june','gemini','cancer'], '2026-06-15', '/checkout',
  'Dog Born in June: Personality Traits, Quirks & What to Expect',
  'dog born in june personality'),
('virgo dog personality', 'dog', 'pet-astrology', 176, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','virgo'], '2026-06-17', '/checkout',
  'Virgo Dogs: The Thoughtful Perfectionists',
  'virgo dog personality'),
('rainbow bridge soul', 'dog', 'memorial', 175, 'D', false, 'rowan-sterling',
  ARRAY['memorial','grief','rainbow-bridge'], '2026-06-19', '/soul-chat',
  'When a Pet Crosses the Rainbow Bridge: A Soul-Level Guide',
  'rainbow bridge pet'),
('cat mood moon phase', 'cat', 'pet-astrology', 174, 'A', false, 'maggie-oshea',
  ARRAY['cat','moon','mood'], '2026-06-22', '/checkout',
  'How to Read Your Cat''s Mood by the Moon Phase',
  'cat moon phase mood'),
('libra dog personality', 'dog', 'pet-astrology', 173, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','libra'], '2026-06-24', '/checkout',
  'Libra Dogs: The Peacemakers',
  'libra dog personality'),
('summer safety sun sign', 'dog', 'breed-personality', 172, 'B', false, 'elena-whitaker',
  ARRAY['breed','summer','safety','health'], '2026-06-26', '/checkout',
  'Summer Safety + Sun-Sign Temperament: Which Dogs Overheat Fastest',
  'dog summer safety temperament'),
('scorpio dog personality', 'dog', 'pet-astrology', 171, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','scorpio'], '2026-06-29', '/checkout',
  'Scorpio Dogs: Intense, Loyal, Unforgettable',
  'scorpio dog personality'),
('cats recognize owner death', 'cat', 'memorial', 170, 'D', false, 'maggie-oshea',
  ARRAY['memorial','cat','recognition'], '2026-07-01', '/soul-chat',
  'Do Cats Recognize Their Owners After Death?',
  'do cats recognize their owners after death'),
('dog soul companion signs', 'dog', 'soulspeak', 169, 'G', false, 'elena-whitaker',
  ARRAY['soulspeak','bond','signs'], '2026-07-03', '/soul-chat',
  'The 9 Signs Your Dog Is Your Soul Companion',
  'signs dog is soul companion'),
('sagittarius dog personality', 'dog', 'pet-astrology', 168, 'A', false, 'callum-hayes',
  ARRAY['zodiac','dog','sagittarius'], '2026-07-06', '/checkout',
  'Sagittarius Dogs: The Adventure-Seekers',
  'sagittarius dog personality'),
('dog dreams meaning', 'dog', 'soulspeak', 167, 'G', false, 'elena-whitaker',
  ARRAY['soulspeak','dreams','behavior'], '2026-07-08', '/soul-chat',
  'What Your Dog Dreams About (and What It Means)',
  'what dogs dream about'),
('fathers day dog dads', 'dog', 'gifts', 166, 'E', false, 'callum-hayes',
  ARRAY['gift','fathers-day','dog-dad'], '2026-07-10', '/gift-v2',
  'Father''s Day Gifts for Dog Dads: The Cosmic Edit',
  'fathers day gift dog dad')
ON CONFLICT DO NOTHING;
